parameters:
#    al_taxonomy.example.class: ActiveLAMP\TaxonomyBundle\Example

services:

    al_taxonomy.subscriber.read_metadata:
        class: ActiveLAMP\TaxonomyBundle\EventListener\ReadMetadata
        arguments:
          - @doctrine.orm.entity_manager
          - @al_taxonomy.metadata
        tags:
          - { name: kernel.event_subscriber }

    al_taxonomy.taxonomy_service:
        class: ActiveLAMP\TaxonomyBundle\Model\TaxonomyService
        arguments:
            - @doctrine.orm.entity_manager
            - @al_taxonomy.metadata

    al_taxonomy.metadata:
        class: ActiveLAMP\TaxonomyBundle\Metadata\TaxonomyMetadata

    al_taxonomy.doctrine.subscriber.related_entities:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\RelatedEntities
        arguments:
            - @al_taxonomy.metadata
        tags:
            - { name: doctrine.event_subscriber }

    al_taxonomy.doctrine.subscriber.vocabulary_fields_loader:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\LoadVocabularyFields
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber }


    al_taxonomy.doctrine.subscriber.remove_entity_terms:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\RemoveEntityTerms
        arguments:
            - @al_taxonomy.metadata
        tags:
            - { name: doctrine.event_subscriber }


    al_taxonomy.constraint.vocabulary_field_validator:
        class: ActiveLAMP\TaxonomyBundle\Validation\Constraint\VocabularyFieldValidator
        arguments:
            - @al_taxonomy.taxonomy_service
        tags:
            - { name: validator.constraint_validator }

    al_taxonomy.serializer.array:
        class: ActiveLAMP\TaxonomyBundle\Serializer\ArraySerializer
        arguments:
            - @al_taxonomy.metadata
            - @al_taxonomy.taxonomy_service