parameters:
#    al_taxonomy.example.class: ActiveLAMP\TaxonomyBundle\Example

services:
    al_taxonomy.metadata:
        class: ActiveLAMP\TaxonomyBundle\Metadata\TaxonomyMetadata

    al_taxonomy.doctrine.metadata_listener:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\TaxonomyMetadataListener
        arguments:
            - @al_taxonomy.metadata
        tags:
            - { name: doctrine.event_subscriber }