parameters:
#    al_taxonomy.example.class: ActiveLAMP\TaxonomyBundle\Example

services:

    al_taxonomy.taxonomy_service:
        class: ActiveLAMP\TaxonomyBundle\Model\TaxonomyService
        arguments:
            - @doctrine.orm.entity_manager
            - @al_taxonomy.metadata

    al_taxonomy.metadata:
        class: ActiveLAMP\TaxonomyBundle\Metadata\TaxonomyMetadata

    al_taxonomy.doctrine.subscriber.metadata:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\TaxonomyMetadataSubscriber
        arguments:
            - @al_taxonomy.metadata
        tags:
            - { name: doctrine.event_subscriber }

    al_taxonomy.doctrine.subscriber.related_entities:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\RelatedEntities
        arguments:
            - @al_taxonomy.metadata
        tags:
            - { name: doctrine.event_subscriber }

    al_taxonomy.doctrine.subscriber.vocabulary_fields_loader:
        class: ActiveLAMP\TaxonomyBundle\Doctrine\EventListener\LoadVocabularyFields
        arguments:
            - @al_taxonomy.metadata
        tags:
            - { name: doctrine.event_subscriber }