ActiveLAMP\Bundle\TaxonomyBundle\Entity\Term:
    exclusion_policy: all
    properties:
        id:
          expose: true
          type: integer

        name:
           expose: true
           type: string

        label:
           expose: true
           serialized_name: label
           access_type: public_methods
           accessor:
              getter: getLabelName
              setter: setLabelName
           type: string

        vocabulary:
            expose: false