ActiveLAMP\Bundle\TaxonomyBundle\Entity\SingularVocabularyField:
    exclusion_policy: all
    virtual_properties:
        getLabelName:
            serialized_name: label
            type: string

        getName:
            serialized_name: name
            type: string

        getId:
            serialized_name: id
            type: integer
