parameters:
    al_taxonomy.vocabulary.class: ActiveLAMP\Bundle\TaxonomyBundle\Entity\Vocabulary
    al_taxonomy.term.class: ActiveLAMP\Bundle\TaxonomyBundle\Entity\Term

services:

    al_taxonomy.subscriber.read_metadata:
        class: ActiveLAMP\Bundle\TaxonomyBundle\EventListener\ReadMetadata
        arguments:
            - @al_taxonomy.taxonomy_service
        tags:
            - { name: kernel.event_subscriber }

    al_taxonomy.vocabulary_repository:
        class: ActiveLAMP\Bundle\TaxonomyBundle\Model\VocabularyRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %al_taxonomy.vocabulary.class%

    al_taxonomy.term_repository:
        class: ActiveLAMP\Bundle\TaxonomyBundle\Model\TermRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %al_taxonomy.term.class%

#    al_taxonomy.vocabulary_field_factory:
#        class: ActiveLAMP\Bundle\TaxonomyBundle\Taxonomy\VocabularyFieldFactory
#        arguments:
#            - @doctrine.orm.entity_manager
#
#    al_taxonomy.entity_manager:
#        class: ActiveLAMP\Bundle\TaxonomyBundle\Taxonomy\TaxonomizedEntityManager
#        arguments:
#            - @al_taxonomy.metadata
#            - @al_taxonomy.vocabulary_repository
#            - @al_taxonomy.vocabulary_field_factory

    al_taxonomy.taxonomy_service:
        class: ActiveLAMP\Bundle\TaxonomyBundle\Taxonomy\TaxonomyService
        arguments:
#            - @al_taxonomy.vocabulary_repository
#            - @al_taxonomy.term_repository
#            - @al_taxonomy.entity_manager
            - @doctrine.orm.entity_manager
#            - @al_taxonomy.metadata

    al_taxonomy.metadata:
        class: ActiveLAMP\Bundle\TaxonomyBundle\Metadata\TaxonomyMetadata
        factory_service: al_taxonomy.taxonomy_service
        factory_method: getMetadata
#
#    al_taxonomy.doctrine.subscriber.related_entities:
#        class: ActiveLAMP\Bundle\TaxonomyBundle\Doctrine\EventListener\RelatedEntities
#        arguments:
#            - @al_taxonomy.metadata
#        tags:
#            - { name: doctrine.event_subscriber }
#
#    al_taxonomy.doctrine.subscriber.vocabulary_fields_loader:
#        class: ActiveLAMP\Bundle\TaxonomyBundle\Doctrine\EventListener\LoadVocabularyFields
#        arguments:
#            - @service_container
#        tags:
#            - { name: doctrine.event_subscriber }
#
#
#    al_taxonomy.doctrine.subscriber.remove_entity_terms:
#        class: ActiveLAMP\Bundle\TaxonomyBundle\Doctrine\EventListener\RemoveEntityTerms
#        arguments:
#            - @al_taxonomy.metadata
#        tags:
#            - { name: doctrine.event_subscriber }


    al_taxonomy.constraint.vocabulary_field_validator:
        class: ActiveLAMP\Bundle\TaxonomyBundle\Validation\Constraint\VocabularyFieldValidator
        arguments:
            - @al_taxonomy.taxonomy_service
        tags:
            - { name: validator.constraint_validator }